console.log('Error Handling And Try Catch');


let a = "neamoth ullah";
if (a !=undefined){
    // throw new console.error("this is not undefined");
}else{
    console.log('This is undefined');
}

try {
    // dskfjadsfjaslf
    console.log('We are inside the try block');
    functionNeamoth();
} catch (error) {
    console.log('Are you ok?');
    console.log(error);
}